inputs:
  1: {slot: 1, type: touch}
  2: {slot: 3, type: light}
  3: {slot: 3, type: light}
  4: {slot: 2, type: light}
others: {background: /home/xg/work/dev/xlcteam/nxtIDE/nxtemu/floor/pyconplbrusel.jpg}
